# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ea9890da2bbb8b24e1105806b096605d74a018451b2763886cbb236274f8df3be72b0984c21d878cb3cec241d26112d90e300190ad44f3b60d8f4f41cd5e929
  api_login: 72db99d0-05dc-0133-cefe-22000a93862b
  api_password: _cIOpimIoDi3RIviWteOTA

test:
  secret_key_base: c126de999a9663b5a26a738404d17d0e3279f7a3a767ad3c8ef1059387cb7f6632d329de35c07bd3d2166e76fb8b99a6eda065818e4ab7f8c786e072136f2b84
  api_login: 72db99d0-05dc-0133-cefe-22000a93862b
  api_password: _cIOpimIoDi3RIviWteOTA

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_login: <%= ENV["API_LOGIN"] %>
  api_password: <%= ENV["API_PASSWORD"] %>

